import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const schema = spawnSync("uv", ["run", "--project", "backend", "--locked", "python", "-m", "backend.api.export_openapi"], {
  cwd: new URL("../../", import.meta.url),
  encoding: "utf8",
});
if (schema.status !== 0) {
  process.stderr.write(schema.stderr);
  process.exit(schema.status ?? 1);
}
const output = "// Generated by npm run generate:api. Do not edit.\n" + astToString(await openapiTS(JSON.parse(schema.stdout)));
const destination = new URL("../src/shared/types/generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== output) {
    throw new Error("API types are out of date. Run npm run generate:api and commit the result.");
  }
} else {
  writeFileSync(destination, output);
}
