// Generated by npm run generate:api. Do not edit.
export interface paths {
    "/api/auction-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auction Versions */
        get: operations["get_auction_versions_api_auction_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auctions */
        get: operations["get_auctions_api_auctions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auction Detail */
        get: operations["get_auction_detail_api_auctions__auction_address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_address}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auction Rounds */
        get: operations["get_auction_rounds_api_auctions__auction_address__rounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_address}/takes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auction Takes */
        get: operations["get_auction_takes_api_auctions__auction_address__takes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chains */
        get: operations["get_chains_api_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rounds */
        get: operations["get_rounds_api_rounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{chain_id}/{block_hash}/{tx_hash}/{log_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round Detail */
        get: operations["get_round_detail_api_rounds__chain_id___block_hash___tx_hash___log_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{chain_id}/{block_hash}/{tx_hash}/{log_index}/live-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round Live Price */
        get: operations["get_round_live_price_api_rounds__chain_id___block_hash___tx_hash___log_index__live_price_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/takers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Takers */
        get: operations["get_takers_api_takers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/takers/{taker_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Taker */
        get: operations["get_taker_api_takers__taker_address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/takers/{taker_address}/takes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Taker Takes */
        get: operations["get_taker_takes_api_takers__taker_address__takes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/takes/{chain_id}/{block_hash}/{tx_hash}/{log_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Take Detail */
        get: operations["get_take_detail_api_takes__chain_id___block_hash___tx_hash___log_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tokens */
        get: operations["get_tokens_api_tokens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tx/{tx_hash}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Tx */
        get: operations["resolve_tx_api_tx__tx_hash__resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuctionActivity */
        AuctionActivity: {
            /** Paid Take Count */
            paid_take_count: number;
            /** Total Participants */
            total_participants: number;
            /** Total Rounds */
            total_rounds: number;
            /** Total Takes */
            total_takes: number;
            /** Total Volume */
            total_volume: string | null;
        };
        /** AuctionDetails */
        AuctionDetails: {
            activity: components["schemas"]["AuctionActivity"];
            /** Address */
            address: string;
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Chain Id */
            chain_id: number;
            /** From Tokens */
            from_tokens: components["schemas"]["TokenModel"][];
            parameters: components["schemas"]["AuctionParameters"];
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Version */
            version?: string | null;
            want_token: components["schemas"]["TokenModel"];
        };
        /** AuctionListItem */
        AuctionListItem: {
            /** Address */
            address: string;
            /** Chain Id */
            chain_id: number;
            /** Latest Activity At */
            latest_activity_at?: string | null;
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Total Rounds */
            total_rounds: number;
            /** Total Takes */
            total_takes: number;
            /** Version */
            version?: string | null;
            want_token?: components["schemas"]["TokenModel"] | null;
        };
        /** AuctionParameters */
        AuctionParameters: {
            /** Auction Length */
            auction_length?: number | null;
            /** Decay Percent */
            decay_percent?: string | null;
            /** Minimum Price */
            minimum_price?: string | null;
            /** Starting Price */
            starting_price?: string | null;
            /** Update Interval */
            update_interval?: number | null;
        };
        /** AuctionRound */
        AuctionRound: {
            /** Auction Length */
            auction_length?: number | null;
            /** Available Amount */
            available_amount?: string | null;
            /** Decay Percent */
            decay_percent?: string | null;
            /** Expected Price Per Unit */
            expected_price_per_unit?: string | null;
            /** From Token */
            from_token?: string | null;
            /** From Token Decimals */
            from_token_decimals?: number | null;
            /** From Token Logo Url */
            from_token_logo_url?: string | null;
            /** From Token Name */
            from_token_name?: string | null;
            /** From Token Price Usd */
            from_token_price_usd?: string | null;
            /** From Token Symbol */
            from_token_symbol?: string | null;
            /** Initial Available */
            initial_available: string;
            /** Is Active */
            is_active: boolean;
            /** Kick Market Quote */
            kick_market_quote?: string | null;
            /** Kick Market Quote Usd */
            kick_market_quote_usd?: string | null;
            /** Kicked At */
            kicked_at: string;
            /** Minimum Price */
            minimum_price?: string | null;
            occurrence: components["schemas"]["SourceOccurrence"];
            /**
             * Paid Usd Take Count
             * @default 0
             */
            paid_usd_take_count: number;
            /** Priced Take Count */
            priced_take_count?: number | null;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Round End */
            round_end?: string | null;
            /** Round Id */
            round_id: number;
            /** Round Start */
            round_start?: string | null;
            /** Scheduled End At */
            scheduled_end_at?: string | null;
            /** Starting Price */
            starting_price?: string | null;
            /** Starting Price Per Unit */
            starting_price_per_unit?: string | null;
            /** Total Actual Paid Usd */
            total_actual_paid_usd?: string | null;
            /** Total Auction Profit Bps */
            total_auction_profit_bps?: number | null;
            /** Total Auction Profit Usd */
            total_auction_profit_usd?: string | null;
            /** Total Market Quote Usd */
            total_market_quote_usd?: string | null;
            /** Total Take Count */
            total_take_count?: number | null;
            /** Total Takes */
            total_takes: number;
            /** Transaction Hash */
            transaction_hash?: string | null;
            /** Update Interval */
            update_interval?: number | null;
            /**
             * Usd Priced Take Count
             * @default 0
             */
            usd_priced_take_count: number;
            /** Version */
            version?: string | null;
            /** Want Token */
            want_token?: string | null;
            /** Want Token Decimals */
            want_token_decimals?: number | null;
            /** Want Token Logo Url */
            want_token_logo_url?: string | null;
            /** Want Token Name */
            want_token_name?: string | null;
            /** Want Token Price Usd */
            want_token_price_usd?: string | null;
            /** Want Token Symbol */
            want_token_symbol?: string | null;
        };
        /** AuctionRoundsResponse */
        AuctionRoundsResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Auction */
            auction: string;
            /** Rounds */
            rounds: components["schemas"]["AuctionRound"][];
            /** Total Rounds */
            total_rounds: number;
        };
        /** AuctionTakesResponse */
        AuctionTakesResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Available Price Sources */
            available_price_sources: components["schemas"]["PriceSourceOption"][];
            /** Takes */
            takes: components["schemas"]["TakeListItem"][];
        };
        /** AuctionVersionOption */
        AuctionVersionOption: {
            /** Auction Count */
            auction_count: number;
            /** Round Count */
            round_count: number;
            /** Version */
            version: string;
        };
        /** AuctionVersionsResponse */
        AuctionVersionsResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Count */
            count: number;
            /** Versions */
            versions: components["schemas"]["AuctionVersionOption"][];
        };
        /** AuctionsResponse */
        AuctionsResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Auctions */
            auctions: components["schemas"]["AuctionListItem"][];
            /** Has Next */
            has_next: boolean;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
        };
        /** ChainInfo */
        ChainInfo: {
            /** Chain Id */
            chain_id: number;
            /** Emoji */
            emoji?: string | null;
            /** Explorer */
            explorer?: string | null;
            /** Icon */
            icon?: string | null;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
        };
        /** ChainsResponse */
        ChainsResponse: {
            /** Chains */
            chains: {
                [key: string]: components["schemas"]["ChainInfo"];
            };
            /** Count */
            count: number;
        };
        /** DiscoveryProblem */
        DiscoveryProblem: {
            /**
             * Code
             * @enum {string}
             */
            code: "unsupported_version" | "lookup_failed" | "deployment_unresolved";
            /** Factory Address */
            factory_address: string;
            /** Version */
            version: string | null;
        };
        /** DiscoveryStatus */
        DiscoveryStatus: {
            /** Known Factory Count */
            known_factory_count: number;
            /** Last Attempt At */
            last_attempt_at: number | null;
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: number | null;
            /** Problems */
            problems: components["schemas"]["DiscoveryProblem"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "partial" | "stale" | "unavailable";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChain */
        HealthChain: {
            /** Block Lag */
            block_lag?: number | null;
            /** Chain Id */
            chain_id: number;
            /** Confirmed Head */
            confirmed_head?: number | null;
            /** Confirmed Head Hash */
            confirmed_head_hash?: string | null;
            /** Confirmed Head Timestamp */
            confirmed_head_timestamp?: number | null;
            discovery: components["schemas"]["DiscoveryStatus"];
            /** Finality Mode */
            finality_mode?: ("finalized" | "confirmations") | null;
            /** Finality Warning */
            finality_warning?: string | null;
            /** Health */
            health: string;
            /** Health Detail */
            health_detail?: string | null;
            /** Indexed */
            indexed: boolean;
            /** Last Confirmed Hash */
            last_confirmed_hash?: string | null;
            /** Last Confirmed Processed */
            last_confirmed_processed?: number | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Finality Advance At */
            last_finality_advance_at?: number | null;
            /** Last Live Processed */
            last_live_processed?: number | null;
            /** Last Reorg At */
            last_reorg_at?: number | null;
            /** Last Success At */
            last_success_at?: number | null;
            /** Latest Rpc Head */
            latest_rpc_head?: number | null;
            /** Latest Rpc Head Timestamp */
            latest_rpc_head_timestamp?: number | null;
            /** Name */
            name: string;
            /** Network Name */
            network_name: string;
            /**
             * Reorg Count
             * @default 0
             */
            reorg_count: number;
            /** Short Name */
            short_name: string;
            /** Start Block */
            start_block?: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Chains */
            chains: components["schemas"]["HealthChain"][];
            /** Count */
            count: number;
        };
        /**
         * IndexedCheckpoint
         * @description Aggregate values include all indexed events; they can extend beyond finality.
         */
        IndexedCheckpoint: {
            /** Confirmed Block */
            confirmed_block: number | null;
            /** Confirmed Block Hash */
            confirmed_block_hash: string | null;
            /** Finality Mode */
            finality_mode: ("finalized" | "confirmations") | null;
            /** Indexed Block */
            indexed_block: number | null;
            /** Indexed Block Hash */
            indexed_block_hash: string | null;
            /** Indexed Timestamp */
            indexed_timestamp: number | null;
        };
        /** PriceSourceOption */
        PriceSourceOption: {
            /** Id */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Label */
            label: string;
            /** Priced Take Count */
            priced_take_count: number;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Total Take Count */
            total_take_count: number;
            /**
             * Usd Priced Take Count
             * @default 0
             */
            usd_priced_take_count: number;
        };
        /** PricingPriceFact */
        PricingPriceFact: {
            /** Canonical Price Usd */
            canonical_price_usd?: string | null;
            /** Capture Lag Seconds */
            capture_lag_seconds: number;
            /** Capture State */
            capture_state: string;
            /** Captured At */
            captured_at: string;
            /** Context Kind */
            context_kind: string;
            /** Id */
            id: number;
            /** Provider Success Count */
            provider_success_count: number;
            /** Providers */
            providers: components["schemas"]["PricingPriceProvider"][];
            /** Request Id */
            request_id?: string | null;
        };
        /** PricingPriceProvider */
        PricingPriceProvider: {
            /** As Of */
            as_of?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Error Retry After Ms */
            error_retry_after_ms?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Participation Status */
            participation_status: string;
            /** Price Usd */
            price_usd?: string | null;
            /** Provider Id */
            provider_id: string;
            /** Provider Position */
            provider_position: number;
            /** Raw Provider Payload */
            raw_provider_payload?: {
                [key: string]: unknown;
            } | null;
            /** Retrieved At */
            retrieved_at?: string | null;
        };
        /** PricingQuoteFact */
        PricingQuoteFact: {
            /** Canonical Amount Out */
            canonical_amount_out?: string | null;
            /** Capture Lag Seconds */
            capture_lag_seconds: number;
            /** Capture State */
            capture_state: string;
            /** Captured At */
            captured_at: string;
            /** Context Kind */
            context_kind: string;
            /** High Amount Out */
            high_amount_out?: string | null;
            /** Id */
            id: number;
            /** Low Amount Out */
            low_amount_out?: string | null;
            /** Provider Success Count */
            provider_success_count: number;
            /** Providers */
            providers: components["schemas"]["PricingQuoteProvider"][];
            /** Request Id */
            request_id?: string | null;
            /** Spread Bps */
            spread_bps?: number | null;
        };
        /** PricingQuoteProvider */
        PricingQuoteProvider: {
            /** Amount In Raw */
            amount_in_raw?: string | null;
            /** Amount Out */
            amount_out?: string | null;
            /** Amount Out Min */
            amount_out_min?: string | null;
            /** Amount Out Min Raw */
            amount_out_min_raw?: string | null;
            /** Amount Out Raw */
            amount_out_raw?: string | null;
            /** As Of */
            as_of?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Error Retry After Ms */
            error_retry_after_ms?: number | null;
            /** Estimated Gas */
            estimated_gas?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Participation Status */
            participation_status: string;
            /** Price Impact Bps */
            price_impact_bps?: number | null;
            /** Provider Id */
            provider_id: string;
            /** Provider Position */
            provider_position: number;
            /** Raw Provider Payload */
            raw_provider_payload?: {
                [key: string]: unknown;
            } | null;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Route */
            route?: {
                [key: string]: unknown;
            } | null;
        };
        /** RoundDetailResponse */
        RoundDetailResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            round: components["schemas"]["RoundListItem"];
        };
        /** RoundListItem */
        RoundListItem: {
            /** Activity At */
            activity_at: string;
            /** Auction Address */
            auction_address: string;
            /** Auction Length */
            auction_length?: number | null;
            /** Available Amount */
            available_amount?: string | null;
            /** Avg Execution Price */
            avg_execution_price?: string | null;
            /** Chain Id */
            chain_id: number;
            /** Decay Percent */
            decay_percent?: string | null;
            /** End At */
            end_at?: string | null;
            /** Expected Price Per Unit */
            expected_price_per_unit?: string | null;
            /** From Token */
            from_token?: string | null;
            /** From Token Decimals */
            from_token_decimals?: number | null;
            /** From Token Logo Url */
            from_token_logo_url?: string | null;
            /** From Token Name */
            from_token_name?: string | null;
            /** From Token Symbol */
            from_token_symbol?: string | null;
            /** Initial Available */
            initial_available?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Kick Market Quote */
            kick_market_quote?: string | null;
            /** Kick Market Quote Usd */
            kick_market_quote_usd?: string | null;
            /** Kicked At */
            kicked_at: string;
            /** Last Take At */
            last_take_at?: string | null;
            /** Last Take Price */
            last_take_price?: string | null;
            /** Minimum Price */
            minimum_price?: string | null;
            occurrence: components["schemas"]["SourceOccurrence"];
            /** Paid Amount */
            paid_amount: string | null;
            /** Paid Take Count */
            paid_take_count: number;
            /**
             * Paid Usd Take Count
             * @default 0
             */
            paid_usd_take_count: number;
            /** Priced Take Count */
            priced_take_count?: number | null;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Pricing By Source */
            pricing_by_source?: {
                [key: string]: components["schemas"]["RoundPricingBySource"];
            } | null;
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Round Id */
            round_id: number;
            /** Scheduled End At */
            scheduled_end_at?: string | null;
            /** Sold Amount */
            sold_amount: string;
            /** Starting Price */
            starting_price?: string | null;
            /** Starting Price Per Unit */
            starting_price_per_unit?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "sold_out" | "expired" | "settled";
            /** Take Count */
            take_count: number;
            /** Total Actual Paid Usd */
            total_actual_paid_usd?: string | null;
            /** Total Auction Profit Bps */
            total_auction_profit_bps?: number | null;
            /** Total Auction Profit Usd */
            total_auction_profit_usd?: string | null;
            /** Total Market Quote Usd */
            total_market_quote_usd?: string | null;
            /** Total Take Count */
            total_take_count?: number | null;
            /** Update Interval */
            update_interval?: number | null;
            /**
             * Usd Priced Take Count
             * @default 0
             */
            usd_priced_take_count: number;
            /** Version */
            version?: string | null;
            /** Want Token */
            want_token?: string | null;
            /** Want Token Decimals */
            want_token_decimals?: number | null;
            /** Want Token Logo Url */
            want_token_logo_url?: string | null;
            /** Want Token Name */
            want_token_name?: string | null;
            /** Want Token Symbol */
            want_token_symbol?: string | null;
        };
        /** RoundLivePrice */
        RoundLivePrice: {
            /** Auction Address */
            auction_address: string;
            /** Chain Id */
            chain_id: number;
            /** Current Price */
            current_price?: string | null;
            /** Current Price Raw */
            current_price_raw?: string | null;
            /** Indexed Block */
            indexed_block: number;
            /** Indexed Block Hash */
            indexed_block_hash: string;
            /** Indexed Timestamp */
            indexed_timestamp: number;
            /** Is Active */
            is_active: boolean;
            occurrence: components["schemas"]["SourceOccurrence"];
            /** Round Id */
            round_id: number;
        };
        /** RoundPricingBySource */
        RoundPricingBySource: {
            /** Priced Take Count */
            priced_take_count: number;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Total Auction Profit Bps */
            total_auction_profit_bps?: number | null;
            /** Total Auction Profit Usd */
            total_auction_profit_usd?: string | null;
            /** Total Market Quote Usd */
            total_market_quote_usd?: string | null;
            /** Total Take Count */
            total_take_count: number;
            /**
             * Usd Priced Take Count
             * @default 0
             */
            usd_priced_take_count: number;
        };
        /** RoundsResponse */
        RoundsResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Has Next */
            has_next: boolean;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Rounds */
            rounds: components["schemas"]["RoundListItem"][];
            /** Total */
            total: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Total */
            total: number;
        };
        /** SearchResult */
        SearchResult: {
            /** Address Or Hash */
            address_or_hash: string;
            /** Chain Id */
            chain_id: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Type
             * @enum {string}
             */
            type: "auction" | "transaction" | "kick_transaction" | "taker" | "token";
        };
        /** SourceOccurrence */
        SourceOccurrence: {
            /** Block Hash */
            block_hash: string;
            /** Chain Id */
            chain_id: number;
            /** Log Index */
            log_index: number;
            /** Tx Hash */
            tx_hash: string;
        };
        /** TakeDetail */
        TakeDetail: {
            /** Amount Paid */
            amount_paid: string | null;
            /** Amount Paid Usd */
            amount_paid_usd?: string | null;
            /** Amount Taken */
            amount_taken: string;
            /** Amount Taken Usd */
            amount_taken_usd?: string | null;
            /** Auction */
            auction: string;
            /** Auction Address */
            auction_address: string;
            /** Base Fee */
            base_fee?: number | null;
            /** Block Number */
            block_number: number;
            /** Chain Id */
            chain_id: number;
            /** Confirmed */
            confirmed: boolean;
            /** Expected Amount Paid */
            expected_amount_paid?: string | null;
            /** From Token */
            from_token?: string | null;
            /** From Token Decimals */
            from_token_decimals?: number | null;
            /** From Token Logo Url */
            from_token_logo_url?: string | null;
            /** From Token Name */
            from_token_name?: string | null;
            /** From Token Symbol */
            from_token_symbol?: string | null;
            /** Gas Price */
            gas_price?: number | null;
            /** Gas Used */
            gas_used?: number | null;
            /** Market Quote Out */
            market_quote_out?: string | null;
            /** Market Quote Out Usd */
            market_quote_out_usd?: string | null;
            occurrence: components["schemas"]["SourceOccurrence"];
            /** Price */
            price?: string | null;
            /** Price Differential Percent */
            price_differential_percent?: number | null;
            /** Price Differential Usd */
            price_differential_usd?: string | null;
            /** Price Facts */
            price_facts?: components["schemas"]["PricingPriceFact"][] | null;
            /** Pricing By Source */
            pricing_by_source?: {
                [key: string]: components["schemas"]["TakePricingBySource"];
            } | null;
            /** Pricing Status */
            pricing_status?: string | null;
            /** Priority Fee */
            priority_fee?: number | null;
            /** Provider Success Count */
            provider_success_count?: number | null;
            /** Quote Facts */
            quote_facts?: components["schemas"]["PricingQuoteFact"][] | null;
            /** Quote Spread Bps */
            quote_spread_bps?: number | null;
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Round Id */
            round_id: number;
            round_occurrence: components["schemas"]["SourceOccurrence"];
            /** Take Quotes */
            take_quotes?: {
                [key: string]: unknown;
            }[] | null;
            /** Take Seq */
            take_seq: number;
            /** Taker */
            taker: string;
            /** Timestamp */
            timestamp: string;
            /** To Token */
            to_token?: string | null;
            /** To Token Decimals */
            to_token_decimals?: number | null;
            /** To Token Logo Url */
            to_token_logo_url?: string | null;
            /** To Token Name */
            to_token_name?: string | null;
            /** To Token Symbol */
            to_token_symbol?: string | null;
            /** Token Prices */
            token_prices?: {
                [key: string]: unknown;
            }[] | null;
            /** Transaction Fee Eth */
            transaction_fee_eth?: number | null;
            /** Transaction Fee Usd */
            transaction_fee_usd?: number | null;
            /** Tx Hash */
            tx_hash: string;
            /** Want Token Price Usd */
            want_token_price_usd?: string | null;
        };
        /** TakeListItem */
        TakeListItem: {
            /** Amount Paid */
            amount_paid: string | null;
            /** Amount Paid Usd */
            amount_paid_usd?: string | null;
            /** Amount Taken */
            amount_taken: string;
            /** Amount Taken Usd */
            amount_taken_usd?: string | null;
            /** Auction */
            auction: string;
            /** Block Number */
            block_number: number;
            /** Chain Id */
            chain_id: number;
            /** Confirmed */
            confirmed: boolean;
            /** Expected Amount Paid */
            expected_amount_paid?: string | null;
            /** From Token */
            from_token?: string | null;
            /** From Token Decimals */
            from_token_decimals?: number | null;
            /** From Token Logo Url */
            from_token_logo_url?: string | null;
            /** From Token Name */
            from_token_name?: string | null;
            /** From Token Symbol */
            from_token_symbol?: string | null;
            /** Market Quote Out */
            market_quote_out?: string | null;
            /** Market Quote Out Usd */
            market_quote_out_usd?: string | null;
            occurrence: components["schemas"]["SourceOccurrence"];
            /** Price */
            price?: string | null;
            /** Price Differential Percent */
            price_differential_percent?: number | null;
            /** Price Differential Usd */
            price_differential_usd?: string | null;
            /** Pricing By Source */
            pricing_by_source?: {
                [key: string]: components["schemas"]["TakePricingBySource"];
            } | null;
            /** Pricing Status */
            pricing_status?: string | null;
            /** Provider Success Count */
            provider_success_count?: number | null;
            /** Quote Spread Bps */
            quote_spread_bps?: number | null;
            /** Receiver */
            receiver?: string | null;
            /** Receiver Name */
            receiver_name?: string | null;
            /** Round Id */
            round_id: number;
            round_occurrence: components["schemas"]["SourceOccurrence"];
            /** Take Seq */
            take_seq: number;
            /** Taker */
            taker: string;
            /** Timestamp */
            timestamp: string;
            /** To Token */
            to_token?: string | null;
            /** To Token Decimals */
            to_token_decimals?: number | null;
            /** To Token Logo Url */
            to_token_logo_url?: string | null;
            /** To Token Name */
            to_token_name?: string | null;
            /** To Token Symbol */
            to_token_symbol?: string | null;
            /** Tx Hash */
            tx_hash: string;
            /** Want Token Price Usd */
            want_token_price_usd?: string | null;
        };
        /** TakePricingBySource */
        TakePricingBySource: {
            /** Market Quote Out */
            market_quote_out?: string | null;
            /** Market Quote Out Usd */
            market_quote_out_usd?: string | null;
            /** Pnl Percent */
            pnl_percent?: number | null;
            /** Pnl Usd */
            pnl_usd?: string | null;
            /** Pricing Status */
            pricing_status?: string | null;
        };
        /** TakerAuctionBreakdown */
        TakerAuctionBreakdown: {
            /** Auction Address */
            auction_address: string;
            /** Chain Id */
            chain_id: number;
            /** First Take */
            first_take?: string | null;
            /** Last Take */
            last_take?: string | null;
            /** Paid Usd Take Count */
            paid_usd_take_count: number;
            /** Priced Take Count */
            priced_take_count: number;
            /** Taker Profit Usd */
            taker_profit_usd?: number | null;
            /** Takes Count */
            takes_count: number;
            /** Volume Usd */
            volume_usd?: number | null;
        };
        /** TakerDetail */
        TakerDetail: {
            /** Active Chains */
            active_chains: number[];
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Auction Breakdown */
            auction_breakdown: components["schemas"]["TakerAuctionBreakdown"][];
            /** Avg Take Size Usd */
            avg_take_size_usd?: number | null;
            /** Avg Taker Profit Usd */
            avg_taker_profit_usd?: number | null;
            /** First Take */
            first_take?: string | null;
            /** Last Take */
            last_take?: string | null;
            /**
             * Paid Usd Take Count
             * @default 0
             */
            paid_usd_take_count: number;
            /** Priced Take Count */
            priced_take_count?: number | null;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Rank By Takes */
            rank_by_takes: number;
            /** Rank By Volume */
            rank_by_volume?: number | null;
            /** Taker */
            taker: string;
            /** Total Taker Profit Usd */
            total_taker_profit_usd?: number | null;
            /** Total Takes */
            total_takes: number;
            /** Total Volume Usd */
            total_volume_usd?: number | null;
            /** Unique Auctions */
            unique_auctions: number;
            /** Unique Chains */
            unique_chains: number;
        };
        /** TakerListResponse */
        TakerListResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /** Has Next */
            has_next: boolean;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Takers */
            takers: components["schemas"]["TakerSummary"][];
            /** Total */
            total: number;
        };
        /** TakerSummary */
        TakerSummary: {
            /** Active Chains */
            active_chains: number[];
            /** Avg Take Size Usd */
            avg_take_size_usd?: number | null;
            /** Avg Taker Profit Usd */
            avg_taker_profit_usd?: number | null;
            /** First Take */
            first_take?: string | null;
            /** Last Take */
            last_take?: string | null;
            /**
             * Paid Usd Take Count
             * @default 0
             */
            paid_usd_take_count: number;
            /** Priced Take Count */
            priced_take_count?: number | null;
            /** Priced Volume Share */
            priced_volume_share?: number | null;
            /** Rank By Takes */
            rank_by_takes: number;
            /** Rank By Volume */
            rank_by_volume?: number | null;
            /** Taker */
            taker: string;
            /** Total Taker Profit Usd */
            total_taker_profit_usd?: number | null;
            /** Total Takes */
            total_takes: number;
            /** Total Volume Usd */
            total_volume_usd?: number | null;
            /** Unique Auctions */
            unique_auctions: number;
            /** Unique Chains */
            unique_chains: number;
        };
        /** TakerTake */
        TakerTake: {
            /** Amount Paid */
            amount_paid?: string | null;
            /** Amount Taken */
            amount_taken?: string | null;
            /** Auction Address */
            auction_address: string;
            /** Chain Id */
            chain_id: number;
            /** Expected Amount Paid */
            expected_amount_paid?: string | null;
            occurrence: components["schemas"]["SourceOccurrence"];
            /** Price */
            price?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Pricing By Source */
            pricing_by_source?: {
                [key: string]: components["schemas"]["TakePricingBySource"];
            } | null;
            /** Pricing Status */
            pricing_status?: string | null;
            /** Round Id */
            round_id: number;
            round_occurrence: components["schemas"]["SourceOccurrence"];
            /** Sequence */
            sequence?: number | null;
            /** Sold */
            sold?: string | null;
            /** Take Seq */
            take_seq?: number | null;
            /** Taker */
            taker: string;
            /** Taker Profit Usd */
            taker_profit_usd?: number | null;
            /** Timestamp */
            timestamp: string;
            /** Tx Hash */
            tx_hash: string;
        };
        /** TakerTakesResponse */
        TakerTakesResponse: {
            /** As Of */
            as_of: {
                [key: string]: components["schemas"]["IndexedCheckpoint"];
            };
            /**
             * Available Price Sources
             * @default []
             */
            available_price_sources: components["schemas"]["PriceSourceOption"][];
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Takes */
            takes: components["schemas"]["TakerTake"][];
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /** TokenModel */
        TokenModel: {
            /** Address */
            address: string;
            /** Chain Id */
            chain_id: number;
            /** Decimals */
            decimals: number;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /** TokensResponse */
        TokensResponse: {
            /** Count */
            count: number;
            /** Tokens */
            tokens: components["schemas"]["TokenModel"][];
        };
        /** TxResolveDestination */
        TxResolveDestination: {
            /** Auction Address */
            auction_address: string;
            /** Chain Id */
            chain_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "round" | "auction";
            occurrence?: components["schemas"]["SourceOccurrence"] | null;
            /** Round Id */
            round_id?: number | null;
            take_occurrence?: components["schemas"]["SourceOccurrence"] | null;
        };
        /** TxResolveResponse */
        TxResolveResponse: {
            destination?: components["schemas"]["TxResolveDestination"] | null;
            /** Kind */
            kind?: ("take" | "kick" | "deployment") | null;
            /** Normalized Tx Hash */
            normalized_tx_hash?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "resolved" | "ambiguous" | "not_found" | "invalid";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_auction_versions_api_auction_versions_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auctions_api_auctions_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
                version?: string[] | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auction_detail_api_auctions__auction_address__get: {
        parameters: {
            query: {
                chain_id: number;
            };
            header?: never;
            path: {
                auction_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionDetails"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auction_rounds_api_auctions__auction_address__rounds_get: {
        parameters: {
            query: {
                chain_id: number;
                round_id?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                auction_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionRoundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auction_takes_api_auctions__auction_address__takes_get: {
        parameters: {
            query: {
                chain_id: number;
                kick_block_hash?: string | null;
                kick_tx_hash?: string | null;
                kick_log_index?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                auction_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionTakesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chains_api_chains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainsResponse"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_rounds_api_rounds_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
                auction_address?: string | null;
                round_id?: number | null;
                status?: string | null;
                pair?: string | null;
                tx_hash?: string | null;
                time_window?: string | null;
                version?: string[] | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_detail_api_rounds__chain_id___block_hash___tx_hash___log_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: number;
                block_hash: string;
                tx_hash: string;
                log_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_live_price_api_rounds__chain_id___block_hash___tx_hash___log_index__live_price_get: {
        parameters: {
            query: {
                indexed_block: number;
                indexed_block_hash: string;
                indexed_timestamp: number;
            };
            header?: never;
            path: {
                chain_id: number;
                block_hash: string;
                tx_hash: string;
                log_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundLivePrice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_takers_api_takers_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
                page?: number;
                limit?: number;
                sort_by?: string;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taker_api_takers__taker_address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taker_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakerDetail"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taker_takes_api_takers__taker_address__takes_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                taker_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakerTakesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_take_detail_api_takes__chain_id___block_hash___tx_hash___log_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: number;
                block_hash: string;
                tx_hash: string;
                log_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tokens_api_tokens_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_tx_api_tx__tx_hash__resolve_get: {
        parameters: {
            query?: {
                chain_id?: number | null;
                block_hash?: string | null;
                log_index?: number | null;
            };
            header?: never;
            path: {
                tx_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TxResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
